export default {
  primaryColor: "#1E90FF",
  primaryTextColor: "#FDFDFD",
  primaryBGColor: "#56ABFF",
  clearChillColor: "#1E90FF",
  clearChillTextColor: "#FDFDFD",
  clearChillBGColor: "#56ABFF",
  watermelonColor: "#FF4757",
  watermelonTextColor: "#FDFDFD",
  watermelonBGColor: "#D25579",
  brightGreekColor: "#3742FA",
  brightGreekTextColor: "#FDFDFD",
  brightGreekBGColor: "#3251FB",
  coralColor: "#FF7F50",
  coralTextColor: "#FDFDFD",
  coralBGColor: "#D28273",
  ufoColor: "#2ED573",
  ufoTextColor: "#FDFDFD",
  ufoBGColor: "#2BC68F"
};
